name: drbeta
favicon: null
layout_spectrum: 0.90703
typography_spectrum: 0.24156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f8485'
    - '#2d3f41'
    - '#a6c5c7'
    - '#27dee9'
    - '#d6fcff'
  brandStrength: 0.9438952289056033
  lightness: 0.87018175679259
  saturation: 0
  rhythmicContrast: 0.3432619229424745
purpose: []
