name: drbeta
favicon: null
layout_spectrum: 0.8164720821660012
typography_spectrum: 0.37836189311929047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9438952289056033
  lightness: 0.87018175679259
  saturation: 0.02983968029730022
  rhythmicContrast: 0.3432619229424745
purpose: []
